openapi: 3.0.0
info:
  title: All my rest api
  description: Rest API for experiment.
  version: 0.1.1
servers:
  - url: http://localhost/rest-php/binhusenstore
    description: Binhusenstore end point
tags:
  - name: category
    description: category of products

paths:
  /category:
    post:
      tags:
        - category
      summary: Lets a user post a new category
      requestBody:
        $ref: "#/components/requestBodies/category"
      responses:
        "201":
          description: Successfully created a new category
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Return_after_post"
        "400":
          $ref: "#/components/responses/400Error"
        "401":
          $ref: "#/components/responses/401Error"
  /categories:
    get:
      tags:
        - category
      summary: Get all categories.
      responses:
        "200":
          $ref: "#/components/responses/getCategory200"
        "401":
          $ref: "#/components/responses/401Error"
        "404":
          description: category not found
  /category/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: The ID of the category
        schema:
          type: string
        example: "WAR220203902"
    get:
      tags:
        - category
      summary: Get category by id.
      responses:
        "200":
          $ref: "#/components/responses/getCategory200"
        "404":
          $ref: "#/components/responses/404Error"
        "401":
          $ref: "#/components/responses/401Error"
    put:
      tags:
        - category
      summary: Update category by id
      requestBody:
        $ref: "#/components/requestBodies/category"
      responses:
        "201":
          $ref: "#/components/responses/200Success"
        "400":
          $ref: "#/components/responses/400Error"
        "401":
          $ref: "#/components/responses/401Error"
        "404":
          $ref: "#/components/responses/404Error"
    delete:
      tags:
        - category
      summary: Delete category by id
      responses:
        "201":
          $ref: "#/components/responses/200Success"
        "400":
          $ref: "#/components/responses/400Error"
        "401":
          $ref: "#/components/responses/401Error"
        "404":
          $ref: "#/components/responses/404Error"
  # End of category end point

components:
  schemas:
    Return_after_post:
      type: object
      properties:
        success:
          type: boolean
          example: true
        id:
          type: string
          example: "WAR22500001"
    category:
      type: object
      properties:
        id:
          type: string
          example: "WAR22500001"
        name_category:
          type: string
          example: "name of category"
  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: false
              message:
                type: string
    401Error:
      description: Invalid Authorization Or Unauthorization
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: false
              message:
                type: string
                default: "You must be authenticated to access this resource."
    200Success:
      description: Success operation
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: true
              message:
                type: string
                default: Update source success
    404Error:
      description: Source not found
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: false
              message:
                type: string
                default: Source not found
    getCategory200:
      description: Success operation
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: true
              data:
                type: array
                items:
                  $ref: "#/components/schemas/category"
  requestBodies:
    category:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name_category:
                type: string
                example: "name of category"
