openapi: 3.0.0
info:
  title: All my rest api
  description: Rest API for experiment.
  version: 0.1.1
servers:
  - url: http://localhost/rest-php/binhusenstore
    description: Binhusenstore end point
tags:
  - name: category
    description: admin_charge of products

paths:
  /admin_charge:
    post:
      tags:
        - admin_charge
      summary: Lets a user post a new admin_charge
      requestBody:
        $ref: "#/components/requestBodies/admin_charge"
      responses:
        "201":
          description: Successfully created a new admin_charge
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Return_after_post"
        "400":
          $ref: "#/components/responses/400Error"
        "401":
          $ref: "#/components/responses/401Error"
    get:
      tags:
        - admin_charge
      summary: Get admin_charge by id.
      responses:
        "200":
          $ref: "#/components/responses/getadmin_charge200"
        "404":
          $ref: "#/components/responses/404Error"
        "401":
          $ref: "#/components/responses/401Error"
    put:
      tags:
        - admin_charge
      summary: Update admin_charge by id
      requestBody:
        $ref: "#/components/requestBodies/admin_charge"
      responses:
        "201":
          $ref: "#/components/responses/200Success"
        "400":
          $ref: "#/components/responses/400Error"
        "401":
          $ref: "#/components/responses/401Error"
        "404":
          $ref: "#/components/responses/404Error"
  # End of admin_charge end point

components:
  schemas:
    Return_after_post:
      type: object
      properties:
        success:
          type: boolean
          example: true
        price:
          type: string
          example: "WAR22500001"
    admin_charge:
      type: object
      properties:
        price:
          type: number
          example: 6000

  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: false
              message:
                type: string
    401Error:
      description: Invalid Authorization Or Unauthorization
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: false
              message:
                type: string
                default: "You must be authenticated to access this resource."
    200Success:
      description: Success operation
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: true
              message:
                type: string
                default: Update source success
    404Error:
      description: Source not found
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: false
              message:
                type: string
                default: Source not found
    getadmin_charge200:
      description: Success operation
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: true
              price:
                type: number
                example: 60000
  requestBodies:
    admin_charge:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              price:
                type: number
                example: 60000
